pyanodon/pyalienlife

prototypes/items/items.lua
Factorio version 1.1.6 (latest as of now). Clicking on "Auog control device" on the toolbar does nothing (worked in earlier versions).
My guess is that they added this flag recently:
https://wiki.factorio.com/Types/ItemPrototypeFlags#.22spawnable.22
Weird thing: flag is not mentioned in https://lua-api.factorio.com/latest/Concepts.html#ItemPrototypeFlags, not sure why.
The Green Button works correctly with it (tested).
Also added `only-in-cursor` flag so controller doesn't needlessly clutter inventory, but that doesn't matter as much.
=> Make unit-controller spawnable

prototypes/buildings/collector-mk02.lua, prototypes/buildings/collector-mk03.lua, prototypes/buildings/collector-mk04.lua, prototypes/buildings/collector.lua, prototypes/upgrades/compost.lua, prototypes/upgrades/simikmetalMK01.lua, prototypes/upgrades/simikmetalMK02.lua, prototypes/upgrades/simikmetalMK03.lua, prototypes/upgrades/simikmetalMK04.lua, prototypes/upgrades/simikmetalMK05.lua, prototypes/upgrades/simikmetalMK06.lua
This is done by making these modules increase pollution output, and forbidding pollution modules in these miners.
resolves pyanodon/pybugreports#45
I have the changes ready to forbid pollution in all other repositories too, so if this one is accepted (or a comment is made to this effect), I'll make pull requests for those too. I didn't want to spam too many pull requests for this one.
=> Collectors and other miners no longer take simik related upgrade modules

prototypes/tips-and-tricks.lua
It used to only trigger when building the vrauk paddock, but now it triggers if you place any building that requires modules to function.
I'll probably improve the tips and tricks further down the line somewhere.
resolves pyanodon/pybugreports#65
=> Fix farm module tip to appear on time.

prototypes/recipes/scrondrix/recipes-scrondrix-raising.lua
Minimum change to unblock people getting to pysci3
Before: 10 -> 8 at chem, 10 -> 13.33 at py3
AfterL 10 -> 12.5 at chem, 10 -> 18 at py3
This will get overwritten by shadowglass doing whatever, but it's to make the release functional before then. This maintains progression, the later recipes are still considered better by YAFC
=> Make initial scrondrix loop (barely) positive

prototypes/recipes/zungror/recipes-zungror-raising.lua
Resolves pyanodon/pybugreports#146
Before:
After:
Example:
=> Make zungror raising loop positive

prototypes/buildings/collector-mk02.lua, prototypes/buildings/collector-mk03.lua, prototypes/buildings/collector-mk04.lua, prototypes/buildings/collector.lua, prototypes/circuit-connector-definitions-pyal.lua
This PR adds circuit connectivity for all four marks of Collectors, so that they can output available resources in the same way that vanilla mining drills can. The image below shows the current implementation for Mks. I-IV, with their outputs facing up, right, down and left respectively.
The relevant definitions are pulled from a new circuit connector definitions file, which can be expanded in future to handle new entities.
Partly addresses [the relevant GitHub issue](https://github.com/pyanodon/pycoalprocessing/issues/237) on the Py Coal Processing repo, but only for Collectors.
=> Circuit connections for Collectors Mks. I-IV

scripts/farming/farm-building-list.lua, scripts/farming/farming.lua
`remote.call('pyalienlife.farming', 'register_farm', 'melon-pen', 'fungi')`
Looking for feedback on the remote interface naming, mostly. Also whether we should keep the pyae stuff here as conditional or proper remote it
=> Add remote interface for registering farms

changelog.txt, scripts/ocula/ocula.lua
Attempt to fix two issues I had with ocula. Firstly, they only checked requested counts when spawned, so if the player walks back within range of the logistic network when the ocula is in transit and a bot delivers an item you end up with excess stuff. Secondly, even though ocula can carry a full stack the first wave of ocula tend to be sent out with only 1 or 2 items as they are sent out the moment anything is used.
- Added check when oculua drop off to make sure they don't overfill.
- Added command to ocula to try and return excess items to original pickup point.
- Changed ocula to always pick up full stack.
- Allowed ocula to work when player is inside logistic networks. 
- Changed tag drawing code to only update when ocula has moved some distance.
=> Added check when oculua drops off to make sure they don't overfill.

scripts/ocula/ocula.lua
Playing more I realized removing the line to deduct the logistic bots incoming was a mistake, the logistic bots were still over filling the player. Also realized that items could be lost if the logistic network was full when the ocula are trying to return items.
=> Ocula fixes

migrations/biofluid.lua, scripts/turd/turd-migration.lua
crash 1: turd-migration.lua
- attempt to index field "turd_bonuses" 
this happens on old saves created before turd_bonuses 
crash 2: biofluid.lua
- attempt to index field 'network_positions'
- biofluid_underground nil pair
this happens on old saves created before biofluid
=> fix nil crash when loading old save

locale/ru/entity.cfg
Corrected the Russian translation of "Fluid Mining Drill" from "Буровая установка для добычи жидкости" (literally translated as "Drilling setup for fluid extraction") to "Жидкостный бур" ("Fluid Drill"). The original translation incorrectly implied fluid extraction, while the corrected version accurately reflects the drill's use of fluids in the mining process.
=> Fix ru Fluid mining drilll locale

changelog.txt, prototypes/upgrades/yaedols.lua
adds the 3 barrels back in while maintaining the proper barrel count of rest of the recipes
=> Fixed yaedols turd path 2 didnt return barrels on 3rd recipe

README.md
Added info to README.md that would have saved me a few hours when I tried to contribute and came across a few problems.
=> Add extra info to make contributing easier.

changelog.txt, scripts/caravan/caravan-prototypes.lua
Fixes https://github.com/pyanodon/pybugreports/issues/650
I turned `inserted_count` into a local, I don't see any reason it should on the table. If it does need to be there, my bad, I can change it.
=> Fix caravan deleting items

prototypes/buildings/flora-collector.lua, prototypes/updates/pyhightech-updates.lua
- As of 2.0.7 Electric Mining Drill is behind research but is a requirement of Flora Collector MK01 which is required to research
- Replace the Electric Mining Drill with a Burner Mining Drill this matches what was done for PyHighTech just unconditionally
Resolves https://github.com/pyanodon/pybugreports/issues/755
=> Don't require electric mining drill before red

changelog.txt, prototypes/upgrades/compost.lua
Fixes https://github.com/pyanodon/pybugreports/issues/794
I made it so that methane is only added to the recipe if pyHT is loaded. I'm not sure if this is the best way to fix it balance-wise, but it should fix the crash
=> Fix crash when pyHT not loaded

changelog.txt, locale/en/caravan.cfg, scripts/caravan/caravan-gui.lua, scripts/caravan/caravan-prototypes.lua, scripts/caravan/caravan.lua
Hello,
I'm working towards improving the circuit conditions in caravans.  Before I get too far, (and because I'm bad at LUA) I wanted to start a PR for feedback.  
At the moment, this adds a "circuit condition with static value" option to caravans, to allow checking if <signal> "=" a value, rather than another signal.  As far as I can tell, the nice circuit gui dialog that the base game has cannot be reused by mods, so this seemed like the cleanest solution, but I might be missing something.
I'd like to also add support for a wider range of conditions, not just "=".  I'm not exactly sure the best way to do this.  My thought is to make a circuit condition class that encapsulates the conditions and conditionals, and exposes an evaluate method, but I'm not sure exactly where to stick this …
=> [WIP] Caravan circuit improvments

changelog.txt, prototypes/buildings/seaweed-crop.lua
Fix for https://github.com/pyanodon/pybugreports/issues/842
Now appropriately sets speeds to 1/4/9/16 when tier is full of modules.
=> Fix base speeds of higher tier seaweed buildings

scripts/caravan/caravan.lua
Clicking on the schedule's play button currently consumes food, even if the destination has just been destroyed.
=> caravan: do not consume food when destination is unavailable

changelog.txt, scripts/turd/turd.lua
Another mod triggering `force.reset_technology_effects()` would result in TURD recipes being re-locked until a technology is researched.
=> Fix TURD recipe re-lock after reset_technology_effects

changelog.txt, prototypes/turd.lua, prototypes/upgrades/auog.lua, prototypes/upgrades/bioreactor.lua, prototypes/upgrades/compost.lua, prototypes/upgrades/fish.lua, prototypes/upgrades/wpu.lua
Centralized TURD building icon code for easier expansion and modification
=> Added a TURD sign to the icons of TURD building recipes (i.e. arquad path 2) so they're easier to differentiate in a GUI

changelog.txt, scripts/caravan/gui/inventories.lua, scripts/caravan/impl.lua
e.g. jerky gives 2 actions instead of 1, brains give 3 actions instead of 2, etc.
This is because when the caravan's "stomach" is empty and it was asked to eat, the caravan would load a new food item but not actually use any fuel.
=> Fix caravan food allows 1 more action per food item than intended

scripts/caravan/gui/inventories.lua
Fixes https://github.com/pyanodon/pybugreports/issues/1122
The cargo tab's contents are only built when `player.controller_type == defines.controllers.character`, so attempting to refresh them crashed.
=> caravan: prevent crash when no character is attached to the player

scripts/caravan/event-handlers/interrupts.lua
Keeping the same interrupt name prevented confirmation.
=> caravan: handle edge-case when renaming interrupt

changelog.txt, scripts/caravan/event-handlers/global.lua
This kept bothering me when accidentally clicking near my mule.
=> Don't open caravan GUI when trying to place a building

changelog.txt, data.lua, locale/en/caravan.cfg, prototypes/buildings/fluid-outpost.lua, prototypes/creatures/fluid-caravan.lua, prototypes/upgrades/creature.lua, scripts/caravan/caravan-prototypes.lua, scripts/caravan/event-handlers/action.lua, scripts/caravan/event-handlers/interrupts.lua, scripts/caravan/gui/action_widgets/comparator.lua, scripts/caravan/gui/action_widgets/number_selection.lua, scripts/caravan/gui/actions.lua, scripts/caravan/gui/cargo_tab.lua, scripts/caravan/gui/edit_interrupt.lua, scripts/caravan/gui/interrupt_conditions.lua, scripts/caravan/gui/inventories.lua, scripts/caravan/gui/main_frame.lua, scripts/caravan/impl/actions.lua, scripts/caravan/utils.lua, settings.lua
Hello,
This PR allows transporting fluids between fluid caravans and their fluid outposts.
The idea stemmed from me not wanting to use trains, being tired of having pipe spaghetti everywhere, and biofluid network being gated behind chem science. It thus felt natural to use caravans.
Fluid temperature is shown if it is greater than the default temperature, temp mixing is also implemented.
I've had to set the `inventory_size` at 0, in order to open the character inventory, to put food in the caravan.
It results in a tiny rectangle in the GUI (see attached screenshot).
"New" icons are attached, as I don't have access to the `pyalienlifegraphics2` repo.
Ideally, a storage tank would be attached on the caravan's back, but I've put my whole graphical skills into making the icons,
so I've …
=> Add fluid caravans

changelog.txt, scripts/caravan/utils.lua
Resolves pyanodon/pybugreports#1145
=> Remove print when opening caravan manager

scripts/turd/turd.lua
When selecting a machine replacement turd, items from the output slot are now reinserted, instead of spilling on the ground.
=> Items no longer spill

changelog.txt, info.json, prototypes/buildings/crane.lua, prototypes/turd.lua
No longer limited to specific type lists, also solves the scaling issue when starting the game (below):
```
4.332 Error ParallelSpriteLoader.cpp:67: Parallel sprite loading failed, falling back to normal sprite loading. The given sprite rectangle (left_top=0x0, right_bottom=64x64) is outside the actual sprite size (left_top=0x0, right_bottom=40x40).
If this is being used as an icon you may need to define the icon_size property.
See the log file for more information.: __pycoalprocessinggraphics__/graphics/icons/gui/turd.png
RAM: 42015/63092 MB, page: 72232/90740 MB, virtual: 6449/134217727 MB, extended virtual: 0 MB
```
=> T.U.R.D. icon overlay refactor

changelog.txt, scripts/caravan/gui/cargo_tab.lua, scripts/caravan/gui/inventories.lua, scripts/caravan/gui/main_frame.lua, scripts/caravan/impl/actions.lua, scripts/caravan/utils.lua
Comparisons didn't account for possibility of `fluidavan-turd`
=> fix crashes clicking TURD fluidavan

scripts/caravan/manager.lua
open outpost a -> without closing outpost a, open outpost b
=> caravans: fix list not updating when switching outposts

changelog.txt, scripts/caravan/gui/edit_interrupt.lua
it was there before but even I didn't know that without testing
=> caravans: add hint for re-assigning interrupt target

scripts/caravan/gui/action_widgets/number_selection.lua, scripts/caravan/gui/actions.lua
wasn't shipped in any update so no changelog for this one
=> caravans: fix missing padding in interrupt target list

changelog.txt, prototypes/buildings/fluid-drill-mk02.lua, prototypes/buildings/fluid-drill-mk03.lua, prototypes/buildings/fluid-drill-mk04.lua
What it says on the tin - larger mining area and lower resource drain
- mk1: 7x7 area, 100% drain
- mk2: 9x9 area, 50% drain
- mk3: 11x11 area, 25% drain
- mk4: 13x13, 12.5% drain
Together, this and https://github.com/pyanodon/pyalternativeenergy/pull/124 resolve https://github.com/pyanodon/pybugreports/issues/1182
=> Buff fluid mining drills

changelog.txt, prototypes/buildings/tuuphra-plantation-mk02.lua, prototypes/buildings/tuuphra-plantation-mk03.lua, prototypes/buildings/tuuphra-plantation-mk04.lua
Currently the Tuuphra plantation mk01 has some of the fluid outputs in slightly different places than the mk02, mk03 and mk04.
* Changes the fluid outputs of the mk01 to be in the same positions as the other tiers.
**Pull request notes**
This will unfortunately break existing mk01 setups :(
Another way to solve this would be to change mk02..mk04 fluid outputs to the mk01 layout;
I personally prefer the mk01 change though, as it changes less overall and thus breaks fewer setups -
At least that is what i think ;b
=> Fix fluid output postions of tuuphra-plantation-mk01

changelog.txt, scripts/caravan/event-handlers/global.lua
Extended fix to include caravans https://github.com/pyanodon/pybugreports/issues/1090
=> Caravan respect "Enable Warning Icon Blinking" in global.lua

scripts/turd/turd.lua
swaps them for the base variant
=> disallow placing ghosts of non-unlocked TURD buildings
