prototypes/functions/functions.lua
There's better ways to do it, but better saved for when functions.lua gets some love as a whole
fixes #56
=> uncap numbered recipes

prototypes/recipes/recipes-mo.lua
Please give feedback if this is meant to be hidden
=> Unhide prepared petri dish

prototypes/technologies/fawogae.lua, prototypes/technologies/genetics.lua, prototypes/technologies/ralesia.lua, prototypes/technologies/vrauks.lua
Fawogae, genetics, ralesia, vrauks
=> Integrate new tech icons

prototypes/buildings/harvester.lua
Relates to pyanodon/pybugreport#9
=> Harvester: Fix vector_to_place_result

prototypes/items/items.lua, prototypes/items/items2.lua, prototypes/recipes/antelope/recipes-antelope-rendering.lua, prototypes/recipes/arqad/recipes-arqad-rendering.lua, prototypes/recipes/arthurian/recipes-arthurian-rendering.lua, prototypes/recipes/auog/recipes-auog-rendering.lua, prototypes/recipes/cottongut/recipes-cottongut-rendering.lua, prototypes/recipes/dhilmos/recipes-dhilmos-rendering.lua, prototypes/recipes/dingrits/recipes-dingrits-rendering.lua, prototypes/recipes/fish/recipes-fish-rendering.lua, prototypes/recipes/kmauts/recipes-kmauts-rendering.lua, prototypes/recipes/korlex/recipes-korlex-rendering.lua, prototypes/recipes/mukmoux/recipes-mukmoux-rendering.lua, prototypes/recipes/phadai/recipes-phadai-rendering.lua, prototypes/recipes/phagnot/recipes-phagnot-rendering.lua, prototypes/recipes/recipes-auto-acessories.lua, prototypes/recipes/recipes-mo.lua, prototypes/recipes/scrondrix/recipes-scrondrix-rendering.lua, prototypes/recipes/simik/recipes-simik-growth-enhancement.lua, prototypes/recipes/simik/recipes-simik-rendering.lua, prototypes/recipes/trits/recipes-trits-rendering.lua, prototypes/recipes/ulric/recipes-ulric-rendering.lua, prototypes/recipes/vonix/recipes-vonix-rendering.lua, prototypes/recipes/vrauks/recipes-vrauk-growth-enhacement.lua, prototypes/recipes/vrauks/recipes-vrauks-rendering.lua, prototypes/recipes/xeno/recipes-xeno-rendering.lua, prototypes/recipes/xyhiphoe/recipes-xyhiphoe-growth-enhancement.lua, prototypes/recipes/xyhiphoe/recipes-xyhiphoe-rendering.lua, prototypes/recipes/zipir/recipes-zipir-rendering.lua, prototypes/recipes/zungror/recipes-zungror-rendering.lua
=> Rendering changes WIP

prototypes/updates/pyhightech-updates.lua
See https://github.com/pyanodon/pyalternativeenergy/pull/13
=> Mechanical parts mk03 balance

locale/en/tips.cfg
This is actually disabled, so I made the locale say so (will save a lot of questions).
resolves pyanodon/pybugreports#7
resolves pyanodon/pybugreports#36
resolves pyanodon/pybugreports#68
=> Add locale for control+T option

prototypes/buildings/kmauts-enclosure-mk01.lua, prototypes/buildings/kmauts-enclosure-mk02.lua, prototypes/buildings/kmauts-enclosure-mk03.lua, prototypes/buildings/kmauts-enclosure-mk04.lua, prototypes/items/items.lua, prototypes/recipes/kmauts/recipes-kmauts-raising.lua
Lower kmauts speed bonus to avoid hitting the cap with mk4 kmauts
=> Special bois

changelog.txt, scripts/caravan/caravan-gui.lua
We were nilling our default value in some cases
=> Fix caravan gui crash on selecting destination

prototypes/updates/pyrawores-updates.lua
So you don't get it one tech after the basic recipe.
Resolves pyanodon/pybugreports#247
=> quartz-mk01 now requires py-science-pack-1

changelog.txt, prototypes/buildings/harvester.lua, prototypes/circuit-connector-definitions.lua
This is a small PR to add circuit connectivity to the Harvester, to better support the use of their associated Automated Smart Farms.
=> Harvester circuit connection

prototypes/recipes/arthurian/recipes-arthurian-modules.lua, prototypes/recipes/kmauts/recipes-kmauts-modules.lua, prototypes/recipes/vonix/recipes-vonix-raising.lua, prototypes/recipes/xeno/recipes-xeno-modules.lua, prototypes/recipes/zungror/recipes-zungror-modules.lua
Fixed are vonix raising + kmauts & xeno modules. 
Edit: Also added Arthurian and Zungror
=> Fixed returned cages

changelog.txt, scripts/caravan/caravan-prototypes.lua
I should have known...
Another place where items are being deleted - same exact mistake.
I also realised I put my changelog entry in the already published version. Oops.
=> Fix caravans deleting food

scripts/caravan/caravan.lua
Included caravan-control ghost detection for the caravan open-dialog event.
=> Fix for bug #687

changelog.txt, info.json, migrations/3.0.24.lua, prototypes/recipes/arthurian/recipes-arthurian.lua, prototypes/recipes/dhilmos/recipes-dhilmos.lua, prototypes/recipes/dingrits/recipes-dingrits.lua, prototypes/recipes/korlex/recipes-korlex.lua, prototypes/recipes/phagnot/recipes-phagnot.lua, prototypes/recipes/simik/recipes-simik.lua, prototypes/recipes/ulric/recipes-ulric.lua, prototypes/recipes/vrauks/recipes-vrauks.lua, prototypes/recipes/zipir/recipes-zipir.lua
Have gone through all food items that have more than 1 liquid input, and have tried to get as much consistency as possible.
Mostly made steam a consistent input.
Added migration to correctly rotate all relevant recipes.
Before:
After Migration:
Freshly Built:
=> Make various liquid inputs of foods consistent

changelog.txt, prototypes/fluids/formamide.lua
Fixes https://github.com/pyanodon/pybugreports/issues/871
=> Mark methanol as catalyst for formadide recipe

prototypes/fluids/bio-oil.lua, prototypes/fluids/depolymerized-organics.lua, prototypes/recipes/recipes-bladder.lua, prototypes/recipes/recipes-photomining.lua, prototypes/recipes/recipes.lua
- https://github.com/pyanodon/pybugreports/issues/1001
- Change_category (both stdlib and the new one) checks for existence this allows simply asking to update and trusting if dependencies are missing nothing will happen
=> Switch to change_category

changelog.txt, prototypes/buildings/wyrmhole.lua
Resolves https://github.com/pyanodon/pybugreports/issues/994
This abuses the fact integration patch can have any layer, but functions identically to the picture.
=> Fixed wyrmhole drawing above everything else.

changelog.txt, scripts/caravan/caravan.lua
Added support for interrupt_targets in py_caravan_condition_operator gui event
=> Fix for Caravan GUI crash with specific condition #1101

changelog.txt, data-updates.lua, prototypes/upgrades/compost.lua
unbarreling sweet syrup now results in a temperature of 10 degrees instead of 0 degrees
=> Fixed unbarreling syrup temperature

prototypes/buildings/crane.lua
Added ingredients for crane mk1 added crane mk2 and mk3
=> Py Crane Recipe

scripts/caravan/event-handlers/action.lua, scripts/caravan/gui/action_widgets/comparator.lua, scripts/caravan/gui/edit_interrupt.lua, scripts/caravan/gui/schedule_tab.lua, scripts/caravan/utils.lua
Stumbled across quite a few bugs while rebasing #304.
=> Caravan fixes

changelog.txt, migrations/TURD-translation-table.lua, scripts/turd/turd.lua
Turds can now be searched by their locale names as well as in game names
Added new fixes to check for nil values before using them as table indexes
=> Locale turd search

scripts/turd/turd.lua
=> Fix TURD recipe re-lock after reset_technology_effects

scripts/caravan/gui/cargo_tab.lua, scripts/caravan/gui/main_frame.lua, scripts/caravan/gui/schedule_tab.lua
There was an annoying twitch when switching tabs.
I've also added padding/margin where needed in both tabs to make the GUI more harmonious.
=> caravan/gui: fix small padding/margin issues

README.md
=> Remove frozen branch mention from README.md

changelog.txt, migrations/3.0.48.json, prototypes/updates/pycoalprocessing-updates.lua, prototypes/upgrades/fish.lua, prototypes/upgrades/wpu.lua, scripts/farming/farm-building-list.lua
Resolves https://github.com/pyanodon/pybugreports/issues/1121
=> WPU and Fish farm normalization

changelog.txt, scripts/caravan/gui/action_widgets/number_selection.lua, scripts/caravan/gui/cargo_tab.lua, scripts/caravan/utils.lua
Replaced with lualib implementation.
Resolves pyanodon/pybugreports#1135
=> Fix crash in format_numeric_value

prototypes/buildings/prandium-lab-mk01.lua, prototypes/buildings/prandium-lab-mk02.lua, prototypes/buildings/prandium-lab-mk03.lua, prototypes/buildings/prandium-lab-mk04.lua, prototypes/buildings/space/space-prandium-lab-mk01.lua, prototypes/recipes/xyhiphoe/recipes-xyhiphoe-modules.lua
=> Prototype typo fixes

changelog.txt
Also normalize periods on this set
=> Update changelog with last two PRs

changelog.txt, migrations/caravan-item-count-3.0.54.lua, scripts/caravan/caravan-prototypes.lua, scripts/caravan/gui/actions.lua, scripts/caravan/gui/interrupt_conditions.lua, scripts/caravan/impl/actions.lua
Mostly fixes for lejendary's cases
=> Another caravan rollup

changelog.txt, scripts/biofluid/biofluid.lua
Doesn't support fully deleting fluids from a save but it's a start
=> Fix biofluid crash with migrated fluids

locale/en/biofluid.cfg, scripts/biofluid/biofluid.lua
=> Fix biofluid crash due to invalid migration.

scripts/ulric/ulric.lua
Added back a function that was lost during caravan overhaul. Additional nil protection
=> Fixed mutagenic transformation

changelog.txt, prototypes/buildings/auog-paddock.lua
Before
After
Similar for MK3 and MK4 buildings.
=> Auog speed rounding

migrations/3.0.54.lua
For people with very specific ratios
=> Add small warning to existing saves about auog paddock speed change

info.json
tired of the portal saying I'm behind
=> bump version to match reality

changelog.txt, prototypes/keyboard-shortcuts.lua, scripts/caravan/event-handlers/interrupts.lua, scripts/caravan/gui/inventories.lua, scripts/caravan/impl/actions.lua
big part is pipette on food slots
=> caravan fix rollup
